
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ani
 */
public class RankingPage extends javax.swing.JFrame {

    /**
     * Creates new form RankingPage
     */
    static int checkM_W;
    static int checkBat_bowl;
    logSinPage lspHomeR=new logSinPage();
   JButton b;
    public RankingPage() {
         if(lspHomeR.checkLogin==1){
            b=new JButton("Update");
            b.setBounds(100,400,100,50);
            b.setBackground(Color.green);
            add(b);
            b.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
                            rankUpdate rpTest=new rankUpdate();
                           
                            rpTest.setVisible(true);
                           
                            setVisible(false);
                            
			}
		});
        }
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        RankOutput = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("    Ranking  Page for Men and Women");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 610, 56));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton1.setText("ICC Men Rankings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 232, 70));

        jButton2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton2.setText("ICC Women Rankings");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 232, 70));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 50));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel11.setText("CricZat");

        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setText("Rankings");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton5.setText("Live Scores");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton6.setText("Players");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(12, 12, 12)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jCheckBox1.setText("Batsman");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jCheckBox2.setText("Bowler");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        RankOutput.setColumns(20);
        RankOutput.setRows(5);
        jScrollPane1.setViewportView(RankOutput);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 250, 300));

        jButton8.setText("Test");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jButton9.setText("ODI");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jButton10.setText("t20");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jCheckBox3.setText("Teams");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rankings_image.jpg"))); // NOI18N
        jLabel3.setText("Up");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 690, 480));

        jButton11.setText("jButton11");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 160, -1));

        jButton12.setText("jButton12");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s ="";
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        RankingPage rp1=new RankingPage();
       if(true){
           rp1.setVisible(true);
           this.dispose();
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        liveScore ls = new liveScore();
        ls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Players().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

       // logSinPage lspHome=new logSinPage();

        if(true){
            if(lspHomeR.checkLogin==1){
                LoggedInPage lgp2=new LoggedInPage();
               
                lgp2.setVisible(true);
                lgp2.name.setText(lspHomeR.userN);
                lgp2.emailShow.setText(lspHomeR.emailS);
               lgp2.numberShow.setText(lspHomeR.phoneNumber);
                
                this.dispose();
                
                this.dispose();
            }
            else{
                lspHomeR.setVisible(true);
                lspHomeR.setLocationRelativeTo(null);
                this.dispose();
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
        if(true){
            checkBat_bowl=1;
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(true)
        {
            checkBat_bowl=2;
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(true)
        {
            checkM_W=1;
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(true)
        {
            
            checkM_W=2;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         if(true){
             
            if(RankOutput.getText()!=null){
                
                RankOutput.setText(null);
            
         if(checkM_W==1 && checkBat_bowl==1){
             try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        } 
         }
         else if(checkM_W==2 && checkBat_bowl==1){
             RankOutput.setText("There is no ranking for test  for women");
         }
         
         else if(checkM_W==1 && checkBat_bowl==2){
             try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_test_bowl` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        } 
         }
         else if(checkM_W==1 && checkBat_bowl==3){
             try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_testteam` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            int email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getInt(3);
           
            rating=result.getInt(4);
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        } 
         }
        
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       if(true){
            if(RankOutput.getText()!=null){
                
                RankOutput.setText(null);
           if(checkM_W==2 && checkBat_bowl==1){
                 try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_women_odi` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
           else if(checkM_W==1 && checkBat_bowl==1){
                  try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_odi` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
           else if(checkM_W==2 && checkBat_bowl==2){
                   try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_women_odi_bowl` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
           else if(checkM_W==1 && checkBat_bowl==2){
                   try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_odi_bowl` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
           else if(checkM_W==1 && checkBat_bowl==3){
             try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_odi_team` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            int email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getInt(3);
           
            rating=result.getInt(4);
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        } 
         }
               else if(checkM_W==2 && checkBat_bowl==3){
             try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_women_odi_team` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            int email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getInt(3);
           
            rating=result.getInt(4);
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        } 
         }
       }
    }//GEN-LAST:event_jButton9ActionPerformed
    }
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      if(true){
             if(RankOutput.getText()!=null){
                
                RankOutput.setText(null);
           if(checkM_W==2 && checkBat_bowl==1){
                 try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_women_t20` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
           else if(checkM_W==1 && checkBat_bowl==1){
                  try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_t20` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
            else if(checkM_W==1 && checkBat_bowl==2){
                  try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_t20_bowl` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
            else if(checkM_W==2 && checkBat_bowl==2){
                  try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_women_t20` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            String email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getString("Country");
            rating=result.getInt("Ratings");
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        }
           }
           else if(checkM_W==1 && checkBat_bowl==3){
             try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_men_t20_team` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            int email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getInt(3);
           
            rating=result.getInt(4);
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        } 
         }
               else if(checkM_W==2 && checkBat_bowl==3){
             try {
          
            String url = "jdbc:mysql://localhost:3306/test";
            String username = "root";
            String password ="";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url,username,password);
            String query ="SELECT * FROM `rank_women_t20_team` ";
            Statement st = con.createStatement();
            ResultSet result;
            result=st.executeQuery(query);
       
            int inp;;
            String pass;
            int email;
            int rating;
            while( result.next()){
            inp=result.getInt("Position");
            pass= result.getString("Name");
            email=result.getInt(3);
           
            rating=result.getInt(4);
             RankOutput.append(" "+inp+"  "+pass+"  "+email+"  "+ rating+"\n");
           
           
        }
        
   
        st.close();
        
        result.close();
            
          
        } catch (Exception ex) {
            System.out.println(ex);
        } 
         }
           
       }
    }//GEN-LAST:event_jButton10ActionPerformed
    }
    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(true){
            checkBat_bowl=3;
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea RankOutput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
